# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailhub', '0002_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, verbose_name='Slug')),
                ('language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='en', max_length=6, verbose_name='Language')),
                ('text_content', models.TextField(verbose_name='Text content')),
                ('html_content', models.TextField(blank=True, null=True, verbose_name='HTML content')),
            ],
            options={
                'verbose_name': 'Email signature',
                'verbose_name_plural': 'Email signatures',
                'ordering': ['slug'],
            },
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='body_html',
            field=models.TextField(blank=True, null=True, verbose_name='Body (HTML)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='email_from',
            field=models.EmailField(blank=True, help_text='Will be sent from "no-reply@domain.com" if left blank.', max_length=254, null=True, verbose_name='Email from'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='signature',
            field=models.CharField(choices=[('none', 'No signature'), ('default', 'Default')], default='default', max_length=100, verbose_name='Signature'),
        ),
    ]
