# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emailhub', '0003_auto_20180228_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='users',
            field=models.ManyToManyField(related_name='emailhub', to=settings.AUTH_USER_MODEL),
        ),
    ]
