# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailhub', '0004_emailmessage_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='to_email',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='user',
        ),
    ]
